### ISSUE TITLE
Sample의 한글 주석이 깨져보입니다.

### ISSUE THREAD

**Issue by vbalien** [okps123/Davi#1]
https://github.com/okps123/Davi/blob/master/DaviSample/WinMain.cpp#L49

샘플소스 인코딩을 확인해주세영.

**Comment by okps123** [comment]
헉, 엘련님 이런 누추한 곳에 어쩐 일이십니까 ㅜㅜ

**Comment by okps123** [comment]
[bcb878e](https://github.com/okps123/Davi/commit/bcb878e9606c1bb79ad2b48ea65512f53b16e589) git encoding 설정으로 해결했습니다.

이런 누차한곳에 어인일로 ㅜ

**Comment by vbalien** [comment]
커밋할때 커밋메시지 끝에 #[이슈넘버] 쓰시면 좋아요.
그리고 이슈 해결되면 이슈 클로즈!
